services:
  catalogue:
    build: ./catalogue
    image: joindevops/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:1.0.0
    container_name: mongodb

  frontend:
    build:
      context: ./frontend
    image: kedas0623/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping

  user:
    build:
      context: ./user
    image: kedas0623/user:1.0.0
    container_name: user
    depends_on:
      - mongodb

  cart:
    build: ./cart
    image : kedas0623/cart:1.0.0
    container_name: cart
    depends_on:
      - redis 
  shipping:
    build: ./
    image: kedas0623/shipping:1.0.0
    container_name: shipping
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    image: kedas0623/mysql:1.0.0
    container_name: mysql   
   

  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: true