services:
  catalogue:
    build: 
      dockerfile: catalogue.Dockerfile
    image: kedas0623/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

  mongodb:
   build:
    dockerfile: mongabd.Dockerfile # it move to mongodb directory
   image: kedas0623/mongabd:1.0.0 # docker build -t kedas0623/mongodb:1.0.0
   container_name: mongabd

networks:
  default:
   driver: bridge
   name: roboshop
   external: false # if true, you need to create manually 
