services:
  catalogue:
    build: ./catalogue
    image: joindevops/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:1.0.0
    container_name: mongodb

  frontend:
    build:
      context: ./frontend
    image: kedas0623/frontend:1.0.0
    container_name: frontend
    depends_on:
      - catalogue
      - user

  user:
    build: ./user
      context: ./user
    image: kedas0623/user:1.0.0
    container_name: user
    depends_on:
      - mongodb

  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: true